// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRx-qUsnGmWp-y8D3CSudbUZOfzOkwexM',
    appId: '1:675032748868:android:6a1ba042a9f05190bf7d11',
    messagingSenderId: '675032748868',
    projectId: 'parking-6d83b',
    storageBucket: 'parking-6d83b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUY3KobFTOOjrd34uDyT7X8GFPMl-BaVM',
    appId: '1:675032748868:ios:06b19a32e92c11b0bf7d11',
    messagingSenderId: '675032748868',
    projectId: 'parking-6d83b',
    storageBucket: 'parking-6d83b.firebasestorage.app',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdR3a5qva4Z2eUOXyh8vLA6D2-qIS3_oY',
    appId: '1:675032748868:web:246a65b982459cf7bf7d11',
    messagingSenderId: '675032748868',
    projectId: 'parking-6d83b',
    storageBucket: 'parking-6d83b.firebasestorage.app',
    authDomain: 'parking-6d83b.firebaseapp.com',
  );
}